CREATE DATABASE lower_hdp50_test;

USE lower_hdp50_test;

CREATE EXTERNAL TABLE IF NOT EXISTS queue
(
    REPORTING_TS                     STRING,
    QUEUE_PATH                       STRING,
    TYPE                             STRING,
    CAPACITY                         STRING,
    USED_CAPACITY                    STRING,
    MAX_CAPACITY                     STRING,
    ABSOLUTE_CAPACITY                STRING,
    ABSOLUTE_MAX_CAPACITY            STRING,
    ABSOLUTE_USED_CAPACITY           STRING,
    NUM_APPLICATIONS                 STRING,
    USED_RESOUCES                    STRING,
    QUEUE_NAME                       STRING,
    STATE                            STRING,
    RESOURCES_USED_MEMORY            STRING,
    RESOURCES_USED_VCORES            STRING,
    HIDE_RESERVATION_QUEUES          STRING,
    ALLOCATED_CONTAINERS             STRING,
    RESERVED_CONTAINERS              STRING,
    PENDING_CONTAINERS               STRING,
    MIN_EFFECTIVE_CAPACITY_MEMORY    STRING,
    MIN_EFFECTIVE_CAPACITY_VCORES    STRING,
    MAX_EFFECTIVE_CAPACITY_MEMORY    STRING,
    MAX_EFFECTIVE_CAPACITY_VCORES    STRING,
    MAXIMUM_ALLOCATION_MEMORY        STRING,
    MAXIMUM_ALLOCATION_VCORES        STRING,
    QUEUE_PRIORITY                   STRING,
    ORDERING_POLICY_INFO             STRING,
    AUTO_CREATE_CHILD_QUEUE_ENABLED  STRING,
    NUM_ACTIVE_APPLICATIONS          STRING,
    NUM_PENDING_APPLICATIONS         STRING,
    NUM_CONTAINERS                   STRING,
    MAX_APPLICATIONS                 STRING,
    MAX_APPLICATIONS_PER_USER        STRING,
    USER_LIMIT                       STRING,
    USER_LIMIT_FACTOR                STRING,
    CONFIGURED_MAX_AM_RESOURCE_LIMIT STRING,
    AM_RESOURCE_LIMIT_MEMORY         STRING,
    AM_RESOURCE_LIMIT_VCORES         STRING,
    USED_AM_RESOURCE_MEMORY          STRING,
    USED_AM_RESOURCE_VCORES          STRING,
    USER_AM_RESOURCE_LIMIT_MEMORY    STRING,
    USER_AM_RESOURCE_LIMIT_VCORES    STRING,
    PREEMPTION_DISABLED              STRING,
    INTRA_QUEUE_PREEMPTION_DISABLED  STRING,
    DEFAULT_PRIORITY                 STRING,
    IS_AUTO_CREATED_LEAF_QUEUE       STRING,
    MAX_APPLICATION_LIFETIME         STRING,
    DEFAULT_APPLICATION_LIFETIME     STRING
)
LOCATION "hdfs://HDP50//user/dstreev/temp"
;

select * from queue limit 10;

show create table queue;