CREATE DATABASE IF NOT EXISTS ${DB};
USE ${DB};

DROP TABLE IF EXISTS QUEUE;

DROP TABLE IF EXISTS hierarchy;

CREATE EXTERNAL TABLE IF NOT EXISTS hierarchy (
    PARENT STRING,
    CHILD STRING,
    CAPACITY DOUBLE,
    MAX_CAPACITY DOUBLE
);

CREATE EXTERNAL TABLE IF NOT EXISTS queue
(
    REPORTING_TS                     STRING,
    QUEUE_PATH                       STRING,
    TYPE                             STRING,
    CAPACITY                         FLOAT,
    USED_CAPACITY                    FLOAT,
    MAX_CAPACITY                     FLOAT,
    ABSOLUTE_CAPACITY                FLOAT,
    ABSOLUTE_MAX_CAPACITY            FLOAT,
    ABSOLUTE_USED_CAPACITY           FLOAT,
    NUM_APPLICATIONS                 INT,
    USED_RESOUCES                    BIGINT,
    QUEUE_NAME                       STRING,
    STATE                            STRING,
    RESOURCES_USED_MEMORY            BIGINT,
    RESOURCES_USED_VCORES            BIGINT,
    HIDE_RESERVATION_QUEUES          STRING,
    ALLOCATED_CONTAINERS             BIGINT,
    RESERVED_CONTAINERS              BIGINT,
    PENDING_CONTAINERS               BIGINT,
    MIN_EFFECTIVE_CAPACITY_MEMORY    BIGINT,
    MIN_EFFECTIVE_CAPACITY_VCORES    BIGINT,
    MAX_EFFECTIVE_CAPACITY_MEMORY    BIGINT,
    MAX_EFFECTIVE_CAPACITY_VCORES    BIGINT,
    MAXIMUM_ALLOCATION_MEMORY        BIGINT,
    MAXIMUM_ALLOCATION_VCORES        BIGINT,
    QUEUE_PRIORITY                   STRING,
    ORDERING_POLICY_INFO             STRING,
    AUTO_CREATE_CHILD_QUEUE_ENABLED  STRING,
    NUM_ACTIVE_APPLICATIONS          INT,
    NUM_PENDING_APPLICATIONS         INT,
    NUM_CONTAINERS                   INT,
    MAX_APPLICATIONS                 INT,
    MAX_APPLICATIONS_PER_USER        INT,
    USER_LIMIT                       INT,
    USER_LIMIT_FACTOR                FLOAT,
    CONFIGURED_MAX_AM_RESOURCE_LIMIT BIGINT,
    AM_RESOURCE_LIMIT_MEMORY         BIGINT,
    AM_RESOURCE_LIMIT_VCORES         BIGINT,
    USED_AM_RESOURCE_MEMORY          BIGINT,
    USED_AM_RESOURCE_VCORES          BIGINT,
    USER_AM_RESOURCE_LIMIT_MEMORY    BIGINT,
    USER_AM_RESOURCE_LIMIT_VCORES    BIGINT,
    PREEMPTION_DISABLED              STRING,
    INTRA_QUEUE_PREEMPTION_DISABLED  STRING,
    DEFAULT_PRIORITY                 STRING,
    IS_AUTO_CREATED_LEAF_QUEUE       STRING,
    MAX_APPLICATION_LIFETIME         STRING,
    DEFAULT_APPLICATION_LIFETIME     STRING
);

DROP TABLE IF EXISTS QUEUE_USAGE;

CREATE EXTERNAL TABLE IF NOT EXISTS queue_usage
(
    REPORTING_TS                    STRING,
    QUEUE_PATH                      STRING,
    CAPACITY                        FLOAT,
    USED_CAPACITY                   FLOAT,
    MAX_CAPACITY                    FLOAT,
    ABSOLUTE_CAPACITY               FLOAT,
    ABSOLUTE_MAX_CAPACITY           FLOAT,
    ABSOLUTE_USED_CAPACITY          FLOAT,
    NUM_APPLICATIONS                INT,
    QUEUE_NAME                      STRING,
    STATE                           STRING,
    HIDE_RESERVATION_QUEUES         STRING,
    ALLOCATED_CONTAINERS            INT,
    RESERVED_CONTAINERS             INT,
    PENDING_CONTAINERS              INT,
    QUEUE_PRIORITY                  STRING,
    ORDERING_POLICY_INFO            STRING,
    AUTO_CREATE_CHILD_QUEUE_ENABLED STRING,
    NUM_ACTIVE_APPLICATIONS         INT,
    NUM_PENDING_APPLICATIONS        INT,
    NUM_CONTAINERS                  INT,
    MAX_APPLICATIONS                INT,
    MAX_APPLICATIONS_PER_USER       INT,
    USER_LIMIT                      INT,
    USER_NUM_ACTIVE_APPLICATIONS    INT,
    USER_NUM_PENDING_APPLICATIONS   INT,
    USER_USERNAME                   STRING,
    USER_USERWEIGHT                 BIGINT,
    USER_ISACTIVE                   STRING,
    USER_RESOURCES_USED_MEMORY      BIGINT,
    USER_RESOURCES_USED_VCORES      BIGINT
);